//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSLoginForms.AuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service.AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/AuthenticationServiceWCFLibrary")]
    [System.SerializableAttribute()]
    public partial class ServiceAuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AuthenticateUserByPassword", ReplyAction="http://tempuri.org/IService/AuthenticateUserByPasswordResponse")]
        PSLoginForms.AuthenticationService.ServiceAuthenticationResponse AuthenticateUserByPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AuthenticateUserByPassword", ReplyAction="http://tempuri.org/IService/AuthenticateUserByPasswordResponse")]
        System.Threading.Tasks.Task<PSLoginForms.AuthenticationService.ServiceAuthenticationResponse> AuthenticateUserByPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AuthenticateUserByOtp", ReplyAction="http://tempuri.org/IService/AuthenticateUserByOtpResponse")]
        PSLoginForms.AuthenticationService.ServiceAuthenticationResponse AuthenticateUserByOtp(string username, string otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AuthenticateUserByOtp", ReplyAction="http://tempuri.org/IService/AuthenticateUserByOtpResponse")]
        System.Threading.Tasks.Task<PSLoginForms.AuthenticationService.ServiceAuthenticationResponse> AuthenticateUserByOtpAsync(string username, string otp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PSLoginForms.AuthenticationService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PSLoginForms.AuthenticationService.IService>, PSLoginForms.AuthenticationService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PSLoginForms.AuthenticationService.ServiceAuthenticationResponse AuthenticateUserByPassword(string username, string password) {
            return base.Channel.AuthenticateUserByPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<PSLoginForms.AuthenticationService.ServiceAuthenticationResponse> AuthenticateUserByPasswordAsync(string username, string password) {
            return base.Channel.AuthenticateUserByPasswordAsync(username, password);
        }
        
        public PSLoginForms.AuthenticationService.ServiceAuthenticationResponse AuthenticateUserByOtp(string username, string otp) {
            return base.Channel.AuthenticateUserByOtp(username, otp);
        }
        
        public System.Threading.Tasks.Task<PSLoginForms.AuthenticationService.ServiceAuthenticationResponse> AuthenticateUserByOtpAsync(string username, string otp) {
            return base.Channel.AuthenticateUserByOtpAsync(username, otp);
        }
    }
}
